### ISSUE TITLE
Resources: Split Resources Sections

### ISSUE THREAD

**Issue by abigger87** [huff-language/huff-docs#12]
## Overview

Currently, there are only two resources listed in https://docs.huff.sh/resources/

We should split resources into at least two sections, one being official Huff Language repositories, with any other sections being third party and all other resources.

**Comment by UnloadingGnat** [comment]
I can start working on this.

**Comment by abigger87** [comment]
Actually one sec - I'm refactoring in https://github.com/huff-language/huff-docs/pull/14

I'll throw up a `Document Style Guide` issue in a sec that would be super helpful if you could tackle!

**Comment by abigger87** [comment]
Completed in #14
