### ISSUE TITLE
Tutorial: Hello World

### ISSUE THREAD

**Issue by abigger87** [huff-language/huff-docs#16]
## Overview

Following what's outlined in the tutorials overview, the Huff Docs should demonstrate how to write a simple "Hello World" contract.

> **Warning**
>
> ~Blocked by #14 due to large-scale docs refactoring~

EDIT: No longer blocked!

**Comment by abigger87** [comment]
Ah yep, go for it!

**Comment by devtooligan** [comment]
@cheethas @abigger87 is this gonna be an actual `helloWorld()` that returns a string?  For Huff I feel like starting with `addTwo(x,y)` is easier because of the  potentially confusing complexities around strings

**Comment by abigger87** [comment]
> @cheethas @abigger87 is this gonna be an actual `helloWorld()` that returns a string?  For Huff I feel like starting with `addTwo(x,y)` is easier because of the  potentially confusing complexities around strings

Let's do both!

**Comment by cheethas** [comment]
Current WIP actually has both!

**Comment by cheethas** [comment]
@abigger87 @devtooligan Would be great if you two could take a look at the current draft.

**Comment by cheethas** [comment]
#24 and #26
