### ISSUE TITLE
Fix: link to tutorial

### ISSUE THREAD

**Issue by devtooligan** [huff-language/huff-docs#22]
Does [this](https://github.com/huff-language/huff-docs/tree/main/src/get-started/compiling) mean 'make' the tutorial?
<img width="834" alt="PNG image 4" src="https://user-images.githubusercontent.com/71567643/179187277-51fbb619-67e0-4997-a5bb-d86452876ef3.png">

**Comment by abigger87** [comment]
Yes!

**Comment by abigger87** [comment]
Should be: https://docs.huff.sh/tutorial/the-basics
