### ISSUE TITLE
404 link on evm-basics page

### ISSUE THREAD

**Issue by Aragar199** [huff-language/huff-docs#38]
Issue:

https://github.com/huff-language/huff-docs/tree/main/src/tutorial/evm-basics 

README.md `Resources` hyperlink returns 404

https://github.com/huff-language/huff-docs/blob/main/src/tutorial/evm-basics/resources/overview

Potential fix:

Change the `Resources` hyperlink from

https://github.com/huff-language/huff-docs/blob/main/src/tutorial/evm-basics/resources/overview

to 

https://docs.huff.sh/resources/overview/

**Comment by UnloadingGnat** [comment]
Nice catch! Pushing a fix now. Thanks!
