### ISSUE TITLE
A small typo in one of the tutorial page 

### ISSUE THREAD

**Issue by bytecode-velocity** [huff-language/huff-docs#54]
![image](https://user-images.githubusercontent.com/29842127/198738819-038f39df-2d19-42e7-bcc2-b44b0d8c8ae7.png)

"we have to an understanding..." -> "we need to have an understanding..."
https://docs.huff.sh/tutorial/hello-world/

**Comment by cheethas** [comment]
thank you for pointing this out, I have created a PR to fix this, much appreciated

**Comment by bytecode-velocity** [comment]
Hey! Hello Maddiaa👋 I guess you're one of the guys working on the development of the Huff language.
I was just trying it out a few days ago. And after putting in some efforts, I finally added two numbers successfully 🙂 Now, I wonder, in Huff can we actually write _every_ kind of contract that could be written in Solidity? Like, some very complex ones like those of Uniswap or other DeFi applications.

**Comment by cheethas** [comment]
Yes absolutely you can! Solidity compiles down to the same opcodes as applications in Huff do so its absolutely possible! https://github.com/pentagonxyz/huffmate here's an example of token contracts written in huff. Im not sure anyone has completed a uniswap implementation in huff but you could for sure give it a go!
